/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author ocean-tor
 */
public class LoadingForm extends javax.swing.JFrame {

    /**
     * Creates new form LoadingForm
     */
    public LoadingForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_text = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        barload = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_text.setForeground(new java.awt.Color(255, 255, 255));
        txt_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_text.setText("LOADING");
        jPanel1.add(txt_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 780, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/investment.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 250, 260));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/lab.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 260, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/canvas.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/graduation.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/grades.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 260, 250));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 240, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MANAGER STUDENTS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 300, 40));

        barload.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(barload, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 484, 910, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/Loading.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LoadingForm load = new LoadingForm();
        load.setVisible(true);

        try {
            for (int i = 0; i <= 110; i += 10) {
                Thread.sleep(1000);
                load.barload.setStringPainted(true);

                if (i == 10) {
                    load.txt_text.setText("Bạn có biết bạn sẽ không thể vừa thở vừa uống nước không?");
                }
                if (i == 20) {
                    load.txt_text.setText("Bạn có biết các bông hoa sẽ nở nhanh hơn nếu được nghe nhạc!");
                }
                if (i == 30) {
                    load.txt_text.setText("Bạn có biết một chú vịt con sẽ xem bất kì ai mà nó nhìn thấy sau 10p sinh ra là mẹ không?");
                }
                if (i == 40) {
                    load.txt_text.setText("Theo nghiên cứu người nào có IQ càng cao sẽ mơ nhiều hơn bình thường!");
                }
                if (i == 50) {
                    load.txt_text.setText("Bạn có biết khả năng bạn bị cá mập cắn còn thấp hơn khi bị quả dừa rơi trúng đầu không?");
                }
                if (i == 60) {
                    load.txt_text.setText("Nếu ô tô có thể bay nó chỉ mất khoảng 1 giờ để ra ngoài vũ trụ");
                }
                if (i == 70) {
                    load.txt_text.setText("Một quả bóng bằng thủy tinh có thể nảy cao hơn một quả bóng bằng cao su");
                }
                if (i == 80) {
                    load.txt_text.setText("75% con người trên Trái Đất chưa từng thấy tuyết");
                }
                if (i == 90) {
                    Thread.sleep(3000);
                    load.txt_text.setText("Woa, load sắp xong dữ liệu rồi nè...");
                }
                if (i == 100) {
                    Thread.sleep(5000);
                    load.txt_text.setText("Chúc bạn sử dụng phần mềm của tôi vui vẻ và an toàn <3");
                }
                if (i == 110) {
                    load.dispose();
                    LoginForm login = new LoginForm();
                    login.setVisible(true);
                }
                load.barload.setValue(i);

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt_text;
    // End of variables declaration//GEN-END:variables
}
