USE ASIGNMENT_JAVA3
GO

-- TẠO BẢNG LOGIN
IF OBJECT_ID('NGUOIDUNG') IS NOT NULL
DROP TABLE NGUOIDUNG
CREATE TABLE NGUOIDUNG
(
TAIKHOAN VARCHAR(50) PRIMARY KEY,
MATKHAU VARCHAR(50) NOT NULL,
VAITRO NVARCHAR(50) NOT NULL
) 
GO

-- TẠO BẢNG SINH VIÊN
IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN
(
MASV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
MAIL VARCHAR(20) NOT NULL,
SDT VARCHAR(10) NOT NULL,
GIOITINH NVARCHAR(3) CHECK (GIOITINH = N'NAM' OR GIOITINH = N'NỮ') NOT NULL,
DCHI NVARCHAR(50) NOT NULL,
HINH NVARCHAR(50) NOT NULL
)
GO

-- TẠO BẢNG ĐIỂM 
IF OBJECT_ID('DIEM') IS NOT NULL
DROP TABLE DIEM 
CREATE TABLE DIEM
(
MADIEM INT PRIMARY KEY ,
MASV VARCHAR(10) NOT NULL,
DTOAN FLOAT NOT NULL,
DVAN FLOAT NOT NULL,
DANH FLOAT NOT NULL,
CONSTRAINT DIEM_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
)
GO

ALTER TABLE DIEM
ADD HOTEN NVARCHAR(50) NOT NULL

INSERT INTO NGUOIDUNG
VALUES ('CB001', '123', N'Cán Bộ Đào tạo')
INSERT INTO NGUOIDUNG
VALUES ('CB002', '123', N'Cán Bộ Đào tạo')
INSERT INTO NGUOIDUNG
VALUES ('GV001', '321', N'Giảng Viên')
INSERT INTO NGUOIDUNG
VALUES ('GV002', '321', N'Giảng Viên')

INSERT INTO SINHVIEN
VALUES ('SV001', N'NGUYỄN LÊ HẢI', 'HAINL@123', '0977256375', N'NAM', N'HÀ TÂY', 'baobinh.jpg')

select * from NGUOIDUNG

INSERT INTO DIEM (MADIEM, HOTEN, MASV, DTOAN, DVAN, DANH) VALUES ( 1, N'NGUYỄN LÊ HẢI', 'SV001', 9, 9, 9)

SELECT * FROM DIEM

SELECT TOP 3*, (DTOAN + DVAN + DANH)/3 AS DTB 
FROM DIEM
ORDER BY DTB DESC

SELECT COUNT(*) AS TOTAL FROM NGUOIDUNG WHERE VAITRO = N'Cán bộ Đào tạo'