USE ASM_JAVA3
GO

-- TẠO BẢNG LOGIN
IF OBJECT_ID('NGUOIDUNG') IS NOT NULL
DROP TABLE NGUOIDUNG
CREATE TABLE NGUOIDUNG
(
TAIKHOAN VARCHAR(50) PRIMARY KEY,
MATKHAU VARCHAR(50) NOT NULL,
VAITRO NVARCHAR(50) NOT NULL
) 
GO

-- TẠO BẢNG SINH VIÊN
IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN
(
MASV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
MAIL VARCHAR(20) NOT NULL,
SDT VARCHAR(10) NOT NULL,
GIOITINH NVARCHAR(3) CHECK (GIOITINH = N'NAM' OR GIOITINH = N'NỮ') NOT NULL,
DCHI NVARCHAR(50) NOT NULL,
HINH IMAGE NOT NULL
)
GO

-- TẠO BẢNG ĐIỂM 
IF OBJECT_ID('DIEM') IS NOT NULL
DROP TABLE DIEM 
CREATE TABLE DIEM
(
MADIEM INT PRIMARY KEY,
MASV VARCHAR(10) NOT NULL,
DTOAN FLOAT NOT NULL,
DVAN FLOAT NOT NULL,
DANH FLOAT NOT NULL,
CONSTRAINT DIEM_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
)
GO

INSERT INTO NGUOIDUNG
VALUES ('CB001', '123', N'Cán Bộ Đào tạo')
INSERT INTO NGUOIDUNG
VALUES ('CB002', '123', N'Cán Bộ Đào tạo')
INSERT INTO NGUOIDUNG
VALUES ('GV001', '321', N'Giảng Viên')
INSERT INTO NGUOIDUNG
VALUES ('GV002', '321', N'Giảng Viên')

select * from NGUOIDUNG